FROM tiagopeixoto/graph-tool

RUN pacman -S --noconfirm python-pip
RUN pip install --upgrade pip
RUN pip install networkx==2.1
RUN pip install python-louvain
RUN pip install pyyaml
RUN pip install seaborn
RUN pip install nbconvert
RUN pip install statsmodels
